name: backend-tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest version protoc
      uses: arduino/setup-protoc@v1
    - name: Install code coverage tool
      uses: taiki-e/install-action@cargo-llvm-cov
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests and collect coverage
      run: cargo llvm-cov --all-features -v
